# Site settings
name: 小可嗒嗒的博客
email: maoxiaoke@outlook.com
author: M/J
url: http://xiaokedada.com
resume_site: http://xiaokedada.com/me/
github: https://github.com/maoxiaoke/
baseurl: ""  #根目录
description: 假如生活欺骗了你，不要悲伤，不要哭泣。
motto: 我们笑着说再见，却深知再见遥遥无期。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xiaokedada
